// 语言文件 - 包含中文、英文和德文的翻译
const languages = {
    zh: {
        // 导航栏
        brandText: "德国独立储能电站投资测算系统",
        navParameters: "边界设定",
        navOpex: "OPEX设定",
        navRevenue: "收入预测",
        navIndicators: "财务指标",
        navStatements: "财务报表",
        navSensitivity: "敏感性分析",
        navBankReport: "融资报告",
        btnHelp: "帮助",
        btnImport: "导入",
        btnSave: "保存",
        btnExport: "导出",
        btnExcel: "Excel",
        btnCalculate: "计算",
        btnLogout: "退出",
        
        // 边界设定界面
        sectionParameters: "📊 项目边界条件设定",
        descParameters: "设置储能电站的基础参数和设备配置",
        cardBasicParams: "电站基础参数",
        labelPower: "电站装机功率",
        hintPower: "德国大型储能项目典型规模",
        labelCapacity: "电站储能容量",
        hintCapacity: "2小时储能配置",
        labelDuration: "储能时长",
        labelOperationYears: "电站运营年限",
        hintOperationYears: "行业标准运营周期",
        labelInitialCapacity: "首年电池可用容量",
        
        cardDegradation: "容量衰减设定",
        labelDegradationMode: "衰减模式",
        optionLinear: "线性衰减（固定年衰减率）",
        optionNonlinear: "非线性衰减（前期快后期慢）",
        optionCycleBased: "循环次数衰减",
        hintDegradationMode: "根据电池特性选择衰减模式",
        labelDegradationRate: "年电池容量衰减率",
        hintDegradationRate: "线性衰减模式：固定年衰减率",
        labelFirstYearDegradation: "首年衰减率",
        hintFirstYearDegradation: "非线性衰减：首年衰减率（通常较高）",
        labelAnnualDecrease: "年衰减率递减幅度",
        hintAnnualDecrease: "非线性衰减：每年衰减率递减幅度",
        labelCyclesPerDegradation: "每1000次循环衰减率",
        hintCyclesPerDegradation: "循环次数衰减：每1000次循环的容量损失",
        labelAnnualCycles: "年运行循环次数",
        hintAnnualCycles: "用于循环次数衰减模式计算",
        labelCapacityThreshold: "容量保持率阈值",
        hintCapacityThreshold: "低于此阈值建议更换电池",
        
        cardFinancing: "融资参数",
        labelEquityRatio: "资本金比例"
    },
    en: {
        // 导航栏
        brandText: "German Independent Energy Storage Power Plant Investment Calculation System",
        navParameters: "Boundary Settings",
        navOpex: "OPEX Settings",
        navRevenue: "Revenue Forecast",
        navIndicators: "Financial Indicators",
        navStatements: "Financial Statements",
        navSensitivity: "Sensitivity Analysis",
        navBankReport: "Financing Report",
        btnHelp: "Help",
        btnImport: "Import",
        btnSave: "Save",
        btnExport: "Export",
        btnExcel: "Excel",
        btnCalculate: "Calculate",
        btnLogout: "Logout",
        
        // 边界设定界面
        sectionParameters: "📊 Project Boundary Conditions",
        descParameters: "Set basic parameters and equipment configuration for the energy storage power plant",
        cardBasicParams: "Basic Power Plant Parameters",
        labelPower: "Installed Power Capacity",
        hintPower: "Typical scale for large energy storage projects in Germany",
        labelCapacity: "Energy Storage Capacity",
        hintCapacity: "2-hour storage configuration",
        labelDuration: "Storage Duration",
        labelOperationYears: "Operation Years",
        hintOperationYears: "Industry standard operation cycle",
        labelInitialCapacity: "Initial Battery Available Capacity",
        
        cardDegradation: "Capacity Degradation Settings",
        labelDegradationMode: "Degradation Mode",
        optionLinear: "Linear Degradation (Fixed Annual Rate)",
        optionNonlinear: "Nonlinear Degradation (Fast at First, Slow Later)",
        optionCycleBased: "Cycle-Based Degradation",
        hintDegradationMode: "Select degradation mode based on battery characteristics",
        labelDegradationRate: "Annual Battery Capacity Degradation Rate",
        hintDegradationRate: "Linear degradation mode: fixed annual degradation rate",
        labelFirstYearDegradation: "First Year Degradation Rate",
        hintFirstYearDegradation: "Nonlinear degradation: first year degradation rate (usually higher)",
        labelAnnualDecrease: "Annual Decrease in Degradation Rate",
        hintAnnualDecrease: "Nonlinear degradation: annual decrease in degradation rate",
        labelCyclesPerDegradation: "Degradation Rate per 1000 Cycles",
        hintCyclesPerDegradation: "Cycle-based degradation: capacity loss per 1000 cycles",
        labelAnnualCycles: "Annual Operation Cycles",
        hintAnnualCycles: "Used for cycle-based degradation mode calculation",
        labelCapacityThreshold: "Capacity Retention Threshold",
        hintCapacityThreshold: "Battery replacement recommended below this threshold",
        
        cardFinancing: "Financing Parameters",
        labelEquityRatio: "Equity Ratio"
    },
    de: {
        // 导航栏
        brandText: "Deutsches unabhängiges Energiespeicher-Kraftwerk-Investitionsberechnungssystem",
        navParameters: "Grenzwerteinstellungen",
        navOpex: "OPEX-Einstellungen",
        navRevenue: "Einnahmenprognose",
        navIndicators: "Finanzindikatoren",
        navStatements: "Finanzberichte",
        navSensitivity: "Sensitivitätsanalyse",
        navBankReport: "Finanzierungsbericht",
        btnHelp: "Hilfe",
        btnImport: "Importieren",
        btnSave: "Speichern",
        btnExport: "Exportieren",
        btnExcel: "Excel",
        btnCalculate: "Berechnen",
        btnLogout: "Abmelden",
        
        // 边界设定界面
        sectionParameters: "📊 Projektgrenzbedingungseinstellungen",
        descParameters: "Stellen Sie die Grundparameter und die Gerätekonfiguration des Energiespeicher-Kraftwerks ein",
        cardBasicParams: "Grundlegende Kraftwerksparameter",
        labelPower: "Installierte Leistung",
        hintPower: "Typische Größe für große Energiespeicherprojekte in Deutschland",
        labelCapacity: "Energiespeicherkapazität",
        hintCapacity: "2-Stunden-Speicher-Konfiguration",
        labelDuration: "Speicherdauer",
        labelOperationYears: "Betriebsjahre",
        hintOperationYears: "Branchenstandardbetriebszyklus",
        labelInitialCapacity: "Erstjährige verfügbare Batteriekapazität",
        
        cardDegradation: "Kapazitätsabbaueinstellungen",
        labelDegradationMode: "Abbaumodus",
        optionLinear: "Lineare Degradation (feste jährliche Rate)",
        optionNonlinear: "Nichtlineare Degradation (zuerst schnell, später langsam)",
        optionCycleBased: "Zyklusbasierte Degradation",
        hintDegradationMode: "Wählen Sie den Abbaumodus basierend auf den Batterieeigenschaften",
        labelDegradationRate: "Jährliche Batteriekapazitätsabbaurate",
        hintDegradationRate: "Linearer Abbaumodus: feste jährliche Abbaurate",
        labelFirstYearDegradation: "Erstjährige Abbaurate",
        hintFirstYearDegradation: "Nichtlineare Degradation: Erstjährige Abbaurate (normalerweise höher)",
        labelAnnualDecrease: "Jährliche Abnahme der Abbaurate",
        hintAnnualDecrease: "Nichtlineare Degradation: jährliche Abnahme der Abbaurate",
        labelCyclesPerDegradation: "Abbaurate pro 1000 Zyklen",
        hintCyclesPerDegradation: "Zyklusbasierte Degradation: Kapazitätsverlust pro 1000 Zyklen",
        labelAnnualCycles: "Jährliche Betriebszyklen",
        hintAnnualCycles: "Verwendet für die zyklusbasierte Abbaumodusberechnung",
        labelCapacityThreshold: "Kapazitätserhaltungsschwelle",
        hintCapacityThreshold: "Batterieersatz empfohlen unterhalb dieser Schwelle",
        
        cardFinancing: "Finanzierungsparameter",
        labelEquityRatio: "Eigenkapitalanteil"
    }
};